title: Default Page

tabs:
# tab
  fields:
    label: Fields
    icon: text
    columns:
    # column
      main:
        width: 1/3
        sections:
        # section
          fields:
            type: fields
            fields:
              text:
                label: Text
                type: textarea

# tab
  media: tabs/media
